# Use an official MongoDB image as the base
FROM mongo:latest

# Expose the default MongoDB port (27017) if needed
EXPOSE 27017

# Define the command to run when starting the container
CMD ["mongod", "--bind_ip_all"]
